[build]
  base = "."
  publish = ".netlify/static"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_API_BASE_URL,NEXT_PUBLIC_GOOGLE_CLIENT_ID,NEXT_PUBLIC_STRIPE_PUBLIC_KEY"

[[plugins]]
  package = "@netlify/next-runtime"

[functions]
  node_bundler = "esbuild"
